database:
  type: sqlite
  # sqlite的path
  path: plugins/AttributeSystem/database.db
  enable: false
  host: localhost
  port: 3306
  user: root
  password: root
  database: root
  #每10分钟同步一次 （tick）
  user-container-sync-time: 12000
options:
  debug: true
  lore-enable: false #Lore读取属性是否启用，默认关闭
  read:
    #当行中有这些之一时，忽略此行属性
    ignores:
      - "//"
      - "§-"
  condition:
    line-condition:
      #单行条件的格式
      #解析:
      # \/ '\'用来转义，   :  属性和单行条件之间的分隔符
      # (?<requirement>.*) : 单行条件们
      # 例： 攻击力: 100/Lv.100,职业: 巫师
      format: '\/(?<requirement>.*)'
      #每个单行条件间的分隔符
      separator: ","
  fight:
    enable: true
    #默认运行的战斗机制组
    default: attack-damage
    #原版抛射物伤害是否会按攻击者射箭时的属性计算 而非射中时的属性
    projectile-cache-data: true
    #是否进行非玩家实体间的战斗计算
    eve-fight-cal: false
    vanilla-armor: true
    #若没有这些权限，则攻击时运行默认的 attack 战斗组
    #当攻击者拥有这个权限时，攻击时将运行 class-a-attack 战斗组
    #权限::战斗组
    attack-fight:
      - as.class.b::class-a-attack
parent-node: "global"
node-priority: 3
