name: "AttributeSystem"
entrypoint: "com.github.zimablue.attrsystem.AttributeSystem"
# the package for annotations scan
packageName: "com.github.zimablue.attrsystem"

version: "1.0-SNAPSHOT"
dependencies:
  - "PlayerDatabase"
  - "PouPlaceholder"