name: "AttributeSystem"
entrypoint: "com.github.zimablue.attrsystem.AttributeSystem"
# the package for annotations scan
packageName: "com.github.zimablue.attrsystem"

version: "1.0-SNAPSHOT"
dependencies:
  - "PlayerDatabase"
  - "PouPlaceholder"
externalDependencies:
  repositories:
    - name: "central"
      url: "https://repo.maven.apache.org/maven2/"
    - name: "aliyun_central"
      url: "https://maven.aliyun.com/repository/central"
  artifacts:
    - "com.ezylang:EvalEx:3.5.0"